### ISSUE TITLE
Get get this to work

### ISSUE THREAD

**Issue by daniel4thsource** [michaelknoch/ng2-cytoscape#1]
Hey I was wondering how I could get this working.

**Comment by michaelknoch** [comment]
hey @daniel4thsource, sorry I havent been notified about your issue.
Is this still relevant?

**Comment by danielamigos** [comment]
Hey Michael! Thanks for getting back to me but I decided to move away from cytoscape since I coundn't find an good implementation of if for Angular 2. Thanks anyways!

**Comment by daniel4thsource** [comment]
Hey Michael! Thanks for getting back to me but I decided to move away from cytoscape since I couldn't find an good implementation of it for Angular 2. Thanks anyways!
