### ISSUE TITLE
How to listen, and handle cytoscape events?

### ISSUE THREAD

**Issue by JimMorrison723** [michaelknoch/ng2-cytoscape#14]
Hi!
I'd like to know how could i listen to changes made in the canvas that has been created, update certain sections of it (add, remove, highlight, etc)
I am using @calvinvette's fork  ([link](https://github.com/calvinvette/ngx-cytoscape)), but i believe the answer should be the same.

And is it possible, to somehow pass the CytoscapeComponent to my component that will place `<ng2-cytoscape>` / `<ngx-cytoscape>`

*Can't see any reference to this in the Readme, samples*

**Comment by calvinvette** [comment]
Yes to both, and they should work similarly in both Michael's original version as well as my fork. You're looking for the CytoscapeComponent child of the ngx-cytoscape component (that gets added in by the module), to which you can bind event handlers to and even directly manipulate the canvas and data sources (nodes & edges).

In the HTML, I've used the bindings:

```
      <ngx-cytoscape [(elements)]="graphData" [style]="style" [layout]="layout"
                     [zoom]="zoom">Preview Rendering...</ngx-cytoscape>  
```

In the Component TS:

```
// This @ViewChild links the rendered <ngx-cytoscape> to this TS object
  @ViewChild(CytoscapeComponent)
  private _cytograph: CytoscapeComponent;
  private _graphData: any = {
    nodes: [], // These are Cyto nodes
    edges: []  // These are Cyto edges
  };

  ngAfterViewInit() {
      const cyLayer = this.cytograph.cy.cyCanvas({
        zIndex: -1
      });

// You can manipulate the canvas directly:
      const cnv: HTMLCanvasElement = cyLayer.getCanvas();

// Manipulate nodes & edges programmatically:
for (const node of this.cytograph.cy.nodes()) {
  // ...
  // node.data.name = ...
  // node.data.x, node.data.y
}

for (const edge of this.cytograph.cy.edges()) {
  // ...
  // edge.data().source
}

// You can register an event hander for render and/or resize:
this.cytograph.cy.on("render cyCanvas.resize", function (evt, src) {
  // ...
});

```

**Comment by JimMorrison723** [comment]
Thank you for your detailed examples, it helped me make it work. Thanks again!
