### ISSUE TITLE
Outdated example and issue when import

### ISSUE THREAD

**Issue by Gimly** [michaelknoch/ng2-cytoscape#3]
Since the latest version of Angular, you don't have directives anymore in the components. Modules should be imported through the imports directives of the `app.module.ts`. The example on the readme is therefore outdated.

When I tried to add the element to the imports, I get the following error message:
`Unexpected value 'NgCytoscape' imported by the module 'AppModule'. Please add a @NgModule annotation.`

**Comment by michaelknoch** [comment]
yes this is correct @Gimly, thanks for the issue. I would be so grateful if you submit a pull request to improve the example code. Assuming you have time and motivation to improve the package.

**Comment by Gimly** [comment]
I would be happy to help, but I'm actually a bit lost on how to fix the error I got. I can't seem to be able to import ng2-cytoscape correctly with the latest version of Angular

**Comment by Gimly** [comment]
Nevermind what I said earlier, I figured it out, created a pull request. This should do it hopefully :)

**Comment by michaelknoch** [comment]
thank you @Gimly 
your changes are merged
