### ISSUE TITLE
Setup auto-deployment to NPM

### ISSUE THREAD

**Issue by Gimly** [michaelknoch/ng2-cytoscape#5]
Hi Michael,

I see that you haven't uploaded the updated version to NPM yet. I think it would be really helpful if you had auto-deployment from the source code. What do you think?

**Comment by michaelknoch** [comment]
yes you're right. I published it right now. How does auto publish work? 
Havent tested this by now.

thanks for your collaboration

**Comment by Gimly** [comment]
Well, turns out it doesn't seem to be that easy. Search quickly and didn't find anything really relevant. Since your code is open source you might be able to do something for free using [AppVeyor](https://www.appveyor.com/), but there's nothing "out of the box" for NPM.

**Comment by michaelknoch** [comment]
ok, so we will skip this for now but thanks for the hint
